apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital

namespace: wac-hospital

resources:
- prepare.kustomization.yaml
- cd.kustomization.yaml
- install.kustomization.yaml
- git-repository.yaml
- xpokorny-project-ufe.image-repository.yaml
- xpokorny-project-ufe.image-policy.yaml
- image-update-automation.yaml